volumes:
  production_traefik: {}
  mysql_data:
    driver: local

networks:
  abedeport-network:
    driver: bridge

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: abedeport-app-prod-test
    restart: unless-stopped
    volumes:
      - ./admin:/var/www/html/admin
      - ./assets:/var/www/html/assets
      - ./noticias:/var/www/html/noticias
      - ./index.html:/var/www/html/index.html
      - ./apache-config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ABEDEPORT
      - DB_USER=abedeport_user
      - DB_PASSWORD=abedeport_strong_password
      - APP_ENV=production
      - APP_DEBUG=false
      - APACHE_SERVER_NAME=localhost  # Changed for local testing
    networks:
      - abedeport-network

  # Traefik Reverse Proxy (modified for local testing)
  traefik:
    image: traefik:3.2.3
    container_name: abedeport-traefik-local-test
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./traefik-local-test.yml:/etc/traefik/traefik.yml  # Use local test config
    ports:
      - '8080:80'   # Map to different port to avoid conflicts
      - '8443:443'  # Map to different port to avoid conflicts
      - '8081:8080' # Traefik dashboard
    networks:
      - abedeport-network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: abedeport-db-prod-test
    restart: unless-stopped
    ports:
      - "3307:3306"  # Different port to avoid conflicts
    environment:
      MYSQL_ROOT_PASSWORD: root_strong_password
      MYSQL_DATABASE: ABEDEPORT
      MYSQL_USER: abedeport_user
      MYSQL_PASSWORD: abedeport_strong_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - abedeport-network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: abedeport-phpmyadmin-prod-test
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: abedeport_user
      PMA_PASSWORD: abedeport_strong_password
      MYSQL_ROOT_PASSWORD: root_strong_password
    depends_on:
      - db
    networks:
      - abedeport-network