log:
  level: DEBUG  # More verbose logging for testing

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

# Remove HTTPS redirect for local testing
http:
  routers:
    # Main application router - HTTP only for local testing
    web-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      service: abedeport-app

    # phpMyAdmin router - HTTP only for local testing  
    phpmyadmin-router:
      rule: "Host(`pma.localhost`)"
      entryPoints:
        - web
      service: phpmyadmin

  services:
    abedeport-app:
      loadBalancer:
        servers:
          - url: http://app:80

    phpmyadmin:
      loadBalancer:
        servers:
          - url: http://phpmyadmin:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

# Enable API for debugging
api:
  dashboard: true
  insecure: true