-- MySQL Script generated by MySQL Workbench
-- Wed Apr  2 21:26:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ABEDEPORT
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ABEDEPORT` ;

-- -----------------------------------------------------
-- Schema ABEDEPORT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ABEDEPORT` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `ABEDEPORT` ;

-- -----------------------------------------------------
-- Table `ABEDEPORT`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `correo` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `estado` TINYINT NULL,
  `is_admin` TINYINT(1) DEFAULT 0,
  `password` VARCHAR(255) NOT NULL,
  `red_social` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABEDEPORT`.`blog_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`blog_posts` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`blog_posts` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `contenido` TEXT NOT NULL,
  `imagen` VARCHAR(255) NULL,
  `autor_id` INT NOT NULL,
  `estado` ENUM('borrador', 'publicado', 'archivado') DEFAULT 'borrador',
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_publicacion` TIMESTAMP NULL,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `slug` VARCHAR(255) UNIQUE,
  `meta_descripcion` VARCHAR(160) NULL,
  `etiquetas` VARCHAR(255) NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_blog_posts_usuario_idx` (`autor_id` ASC),
  INDEX `idx_estado` (`estado` ASC),
  INDEX `idx_fecha_publicacion` (`fecha_publicacion` ASC),
  CONSTRAINT `fk_blog_posts_usuario`
    FOREIGN KEY (`autor_id`)
    REFERENCES `ABEDEPORT`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Insert sample data
-- -----------------------------------------------------

-- Insert sample usuarios
INSERT INTO usuario (nombre, apellido, correo, documento, estado, is_admin, password, red_social) VALUES 
('Administrador', 'Sistema', 'admin@abedeport.com', '12345678', 1, 1, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin'),
('Juan', 'Pérez', 'juan.perez@email.com', '87654321', 1, 0, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'facebook'),
('María', 'García', 'maria.garcia@email.com', '11223344', 1, 0, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'instagram')
ON DUPLICATE KEY UPDATE id_usuario = id_usuario;


-- -----------------------------------------------------
-- Table `ABEDEPORT`.`tournaments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`tournaments` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`tournaments` (
  `id_tournament` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `deporte` ENUM('futbol', 'futsal', 'baloncesto', 'voleibol') NOT NULL,
  `temporada` VARCHAR(50) NOT NULL,
  `estado` ENUM('activo', 'finalizado', 'proximo') DEFAULT 'activo',
  `fecha_inicio` DATE,
  `fecha_fin` DATE,
  PRIMARY KEY (`id_tournament`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ABEDEPORT`.`equipos_tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`equipos_tournament` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`equipos_tournament` (
  `id_equipo_tournament` INT NOT NULL AUTO_INCREMENT,
  `id_tournament` INT NOT NULL,
  `nombre_equipo` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NULL,
  `pais` VARCHAR(100) NULL,
  `logo` VARCHAR(255) NULL,
  `partidos_jugados` INT DEFAULT 0,
  `partidos_ganados` INT DEFAULT 0,
  `partidos_perdidos` INT DEFAULT 0,
  `partidos_empatados` INT DEFAULT 0,
  `puntos_favor` INT DEFAULT 0,
  `puntos_contra` INT DEFAULT 0,
  `puntos_totales` INT DEFAULT 0,
  `posicion` INT NULL,
  `destacado` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_equipo_tournament`),
  INDEX `fk_equipos_tournament_tournaments_idx` (`id_tournament` ASC),
  INDEX `idx_tournament_posicion` (`id_tournament` ASC, `posicion` ASC),
  CONSTRAINT `fk_equipos_tournament_tournaments`
    FOREIGN KEY (`id_tournament`)
    REFERENCES `ABEDEPORT`.`tournaments` (`id_tournament`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- Insert sample blog posts
INSERT INTO blog_posts (titulo, contenido, autor_id, estado, fecha_publicacion, slug, meta_descripcion, etiquetas) VALUES 
('Bienvenidos a AEDEPORT', 'Somos una organización dedicada al desarrollo deportivo y la recreación. Nuestro objetivo es promover un estilo de vida saludable a través del deporte.', 1, 'publicado', NOW(), 'bienvenidos-aededeport', 'Descubre AEDEPORT, tu organización deportiva líder en recreación y desarrollo deportivo.', 'futbol, baloncesto'),
('Nuevos Programas de Entrenamiento', 'Hemos implementado nuevos programas de entrenamiento para todas las edades y niveles. Incluyen fútbol, baloncesto, futsal y voleibol.', 1, 'publicado', NOW(), 'nuevos-programas-entrenamiento', 'Conoce nuestros nuevos programas de entrenamiento deportivo para todas las edades.', 'futbol, futsal, baloncesto, voleibol'),
('Resultados del Torneo Regional', 'Nuestros equipos obtuvieron excelentes resultados en el torneo regional. Los Leones FC se coronaron campeones en fútbol.', 1, 'publicado', NOW(), 'resultados-torneo-regional', 'Celebra con nosotros los logros de nuestros equipos en el torneo regional.', 'futbol'),
('Torneo Multideporte AEDEPORT 2025', 'Gran evento que incluye competencias de múltiples deportes. Participan equipos de fútbol, baloncesto y voleibol en una experiencia deportiva única.', 1, 'publicado', NOW(), 'torneo-multideporte-2025', 'Evento multideporte con fútbol, baloncesto y voleibol', 'futbol, baloncesto, voleibol')
ON DUPLICATE KEY UPDATE id_post = id_post;

-- Insert sample tournaments
INSERT INTO tournaments (nombre, deporte, temporada, estado, fecha_inicio, fecha_fin) VALUES 
('Liga Profesional de Fútbol', 'futbol', '2025', 'activo', '2025-01-01', '2025-06-30'),
('Copa Nacional de Futsal', 'futsal', '2025', 'activo', '2025-02-01', '2025-05-30'),
('Torneo de Baloncesto Regional', 'baloncesto', '2025', 'activo', '2025-01-15', '2025-07-15'),
('Liga de Voleibol Profesional', 'voleibol', '2025', 'activo', '2025-03-01', '2025-08-30')
ON DUPLICATE KEY UPDATE id_tournament = id_tournament;

-- Insert sample tournament standings
INSERT INTO equipos_tournament (id_tournament, nombre_equipo, ciudad, pais, logo, partidos_jugados, partidos_ganados, partidos_perdidos, partidos_empatados, puntos_favor, puntos_contra, puntos_totales, posicion, destacado) VALUES 
(1, 'Real Madrid Deportivo', 'Madrid', 'España', 'assets/images/esports/logos/alchemists-22x25.png', 16, 14, 2, 0, 28, 14, 42, 1, 0),
(1, 'FC Barcelona Elite', 'Barcelona', 'España', 'assets/images/esports/logos/alchemists-22x25.png', 16, 12, 4, 0, 27, 13, 36, 2, 0),
(1, 'Club Deportivo AEDEPORT', 'Medellín', 'Colombia', 'assets/images/esports/logos/alchemists-22x25.png', 16, 11, 5, 0, 26, 11, 33, 3, 1),
(1, 'Atlético Valencia', 'Valencia', 'España', 'assets/images/esports/logos/alchemists-22x25.png', 16, 9, 7, 0, 20, 19, 27, 4, 0),
(1, 'Sevilla FC Pro', 'Sevilla', 'España', 'assets/images/esports/logos/alchemists-22x25.png', 16, 8, 8, 0, 18, 22, 24, 5, 0),
(3, 'Lakers AEDEPORT', 'Los Ángeles', 'Colombia', 'assets/images/esports/logos/alchemists-22x25.png', 20, 18, 2, 0, 1850, 1620, 36, 1, 1),
(3, 'Warriors Elite', 'San Francisco', 'Estados Unidos', 'assets/images/esports/logos/alchemists-22x25.png', 20, 16, 4, 0, 1780, 1650, 32, 2, 0),
(3, 'Celtics Pro', 'Boston', 'Estados Unidos', 'assets/images/esports/logos/alchemists-22x25.png', 20, 14, 6, 0, 1720, 1680, 28, 3, 0),
(3, 'Heat Miami', 'Miami', 'Estados Unidos', 'assets/images/esports/logos/alchemists-22x25.png', 20, 12, 8, 0, 1680, 1720, 24, 4, 0)
ON DUPLICATE KEY UPDATE id_equipo_tournament = id_equipo_tournament;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; 