-- MySQL Script generated by MySQL Workbench
-- Wed Apr  2 21:26:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ABEDEPORT
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ABEDEPORT` ;

-- -----------------------------------------------------
-- Schema ABEDEPORT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ABEDEPORT` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `ABEDEPORT` ;

-- -----------------------------------------------------
-- Table `ABEDEPORT`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `correo` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `estado` TINYINT NULL,
  `password` VARCHAR(255) NOT NULL,
  `red_social` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ABEDEPORT`.`espacio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`espacio` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`espacio` (
  `id_espacio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_espacio`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ABEDEPORT`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`equipo` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`equipo` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `disiplina` VARCHAR(50) NOT NULL,
  `categoria` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_equipo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ABEDEPORT`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`evento` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_fin` TIME NOT NULL,
  `tipo_evento` TINYINT NOT NULL,
  `espacio_id_espacio` INT NOT NULL,
  `equipo_id_equipo` INT NOT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `fk_evento_espacio_idx` (`espacio_id_espacio` ASC),
  INDEX `fk_evento_equipo1_idx` (`equipo_id_equipo` ASC),
  CONSTRAINT `fk_evento_espacio`
    FOREIGN KEY (`espacio_id_espacio`)
    REFERENCES `ABEDEPORT`.`espacio` (`id_espacio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_equipo1`
    FOREIGN KEY (`equipo_id_equipo`)
    REFERENCES `ABEDEPORT`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ABEDEPORT`.`jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`jugador` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`jugador` (
  `id_jugador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `edad` INT NOT NULL,
  `foto` BLOB NULL,
  `equipo_id_equipo` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_jugador`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_jugador_equipo1_idx` (`equipo_id_equipo` ASC),
  INDEX `fk_jugador_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_jugador_equipo1`
    FOREIGN KEY (`equipo_id_equipo`)
    REFERENCES `ABEDEPORT`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `ABEDEPORT`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ABEDEPORT`.`blog_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABEDEPORT`.`blog_posts` ;

CREATE TABLE IF NOT EXISTS `ABEDEPORT`.`blog_posts` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `contenido` TEXT NOT NULL,
  `imagen` VARCHAR(255) NULL,
  `autor_id` INT NOT NULL,
  `estado` ENUM('borrador', 'publicado', 'archivado') DEFAULT 'borrador',
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_publicacion` TIMESTAMP NULL,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `slug` VARCHAR(255) UNIQUE,
  `meta_descripcion` VARCHAR(160) NULL,
  `etiquetas` VARCHAR(255) NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_blog_posts_usuario_idx` (`autor_id` ASC),
  INDEX `idx_estado` (`estado` ASC),
  INDEX `idx_fecha_publicacion` (`fecha_publicacion` ASC),
  CONSTRAINT `fk_blog_posts_usuario`
    FOREIGN KEY (`autor_id`)
    REFERENCES `ABEDEPORT`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Insert sample data
-- -----------------------------------------------------

-- Insert sample usuarios
INSERT INTO usuario (nombre, apellido, correo, documento, estado, password, red_social) VALUES 
('Administrador', 'Sistema', 'admin@abedeport.com', '12345678', 1, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin'),
('Juan', 'Pérez', 'juan.perez@email.com', '87654321', 1, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'facebook'),
('María', 'García', 'maria.garcia@email.com', '11223344', 1, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'instagram')
ON DUPLICATE KEY UPDATE id_usuario = id_usuario;

-- Insert sample espacios
INSERT INTO espacio (nombre) VALUES 
('Cancha de Fútbol'),
('Gimnasio'),
('Piscina'),
('Pista de Atletismo'),
('Cancha de Baloncesto')
ON DUPLICATE KEY UPDATE id_espacio = id_espacio;

-- Insert sample equipos
INSERT INTO equipo (nombre, disiplina, categoria) VALUES 
('Leones FC', 'Fútbol', 'Senior'),
('Águilas BB', 'Baloncesto', 'Juvenil'),
('Tiburones Nat', 'Natación', 'Infantil'),
('Runners AT', 'Atletismo', 'Senior')
ON DUPLICATE KEY UPDATE id_equipo = id_equipo;

-- Insert sample eventos
INSERT INTO evento (nombre, hora_inicio, fecha, hora_fin, tipo_evento, espacio_id_espacio, equipo_id_equipo) VALUES 
('Entrenamiento Fútbol', '08:00:00', '2025-01-15', '10:00:00', 1, 1, 1),
('Partido Baloncesto', '15:00:00', '2025-01-16', '17:00:00', 2, 5, 2),
('Clase Natación', '14:00:00', '2025-01-17', '15:30:00', 1, 3, 3),
('Carrera Atletismo', '07:00:00', '2025-01-18', '09:00:00', 2, 4, 4)
ON DUPLICATE KEY UPDATE id_evento = id_evento;

-- Insert sample jugadores
INSERT INTO jugador (nombre, edad, equipo_id_equipo, usuario_id_usuario) VALUES 
('Carlos López', 25, 1, 2),
('Ana Rodríguez', 18, 2, 3),
('Luis Martínez', 12, 3, 2),
('Sofia Torres', 30, 4, 3)
ON DUPLICATE KEY UPDATE id_jugador = id_jugador;

-- Insert sample blog posts
INSERT INTO blog_posts (titulo, contenido, autor_id, estado, fecha_publicacion, slug, meta_descripcion, etiquetas) VALUES 
('Bienvenidos a AEDEPORT', 'Somos una organización dedicada al desarrollo deportivo y la recreación. Nuestro objetivo es promover un estilo de vida saludable a través del deporte.', 1, 'publicado', NOW(), 'bienvenidos-aededeport', 'Descubre AEDEPORT, tu organización deportiva líder en recreación y desarrollo deportivo.', 'deporte, recreación, salud'),
('Nuevos Programas de Entrenamiento', 'Hemos implementado nuevos programas de entrenamiento para todas las edades y niveles. Incluyen fútbol, baloncesto, natación y atletismo.', 1, 'publicado', NOW(), 'nuevos-programas-entrenamiento', 'Conoce nuestros nuevos programas de entrenamiento deportivo para todas las edades.', 'entrenamiento, programas, deporte'),
('Resultados del Torneo Regional', 'Nuestros equipos obtuvieron excelentes resultados en el torneo regional. Los Leones FC se coronaron campeones en fútbol.', 1, 'publicado', NOW(), 'resultados-torneo-regional', 'Celebra con nosotros los logros de nuestros equipos en el torneo regional.', 'torneo, resultados, campeones')
ON DUPLICATE KEY UPDATE id_post = id_post;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; 