log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ':443'

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@abedeport.abejorralmuchopueblo.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:

    # Main application router
    web-router:
      rule: "Host(`abedeport.abejorralmuchopueblo.com`)"
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      service: abedeport-app
      priority: 1
      tls:
        certResolver: letsencrypt

    # phpMyAdmin router
    phpmyadmin-router:
      rule: "Host(`pma.abedeport.abejorralmuchopueblo.com`)"
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      service: phpmyadmin
      priority: 1
      tls:
        certResolver: letsencrypt

  middlewares:
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive"
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
  
  services:
    abedeport-app:
      loadBalancer:
        servers:
          - url: http://app:80

    phpmyadmin:
      loadBalancer:
        servers:
          - url: http://phpmyadmin:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true